spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shipper_connect
    username: postgres
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration
    enabled: true

