spring:
  datasource:
    url: jdbc:postgresql://containers-us-west-71.railway.app:6992/railway
    username: postgres
    password: cQTfJRz130ElGSY7bfED
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration
    enabled: true

